#!Freemarker
# Deze query geeft een result set met alle plaatsen die binnen de opgegeven
# gemeente liggen. 
#
# Required Parameters:
#   gemeentecode       de BAG gemeente code.
# 
# Optional parameters:
#   limit              het maximum aantal te tonen resultaten
#   offset             de offset in de totale result set van waar te starten 
#                      met het tonen van resultaten.
#

PREFIX dm:   <http://www.digimelding.nl/2013/08/dm#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX reva: <http://data.reva.nl/2013/07/reva#>
PREFIX rela: <http://www.digimelding.nl/2013/11/relaties#>

SELECT ?plaatscode
WHERE {
  GRAPH <http://www.digimelding.nl/2013/11/relaties> {
    <http://www.kadaster.nl/gemeente/${gemeentecode}> rdf:type rela:Gemeente ;
      rela:heeftPlaats ?plaatscode .
  }
}
LIMIT ${limit} OFFSET ${offset}
