#!Freemarker 
#
# Deze query geeft het aantal registraties met een BSN per loketgemeente
# terug. 
#
# Required Parameters:
# 
# Optional parameters:
#   gemeenteCode       de gemeente waarvoor deze rapportage geldt.
#   vanafDatum         de datum vanaf indien aanwezig anders vandaag
#   totenmetDatum      de datum tot en met indien aanwezig anders vandaag
#   limit              het maximum aantal te tonen resultaten
#   offset             de offset in de totale result set van waar te starten 
#                      met het tonen van resultaten.
#
# REMARK:
#   The parameters 'stamIndexName' can be ignored safely when executing this 
#   query. They are used by the AStore framework:
#     'stamIndexName'   Will be replaced with the actual index name used
#                       by the framework. This name is configuration hence
#                       the need to use a parameter.
#

<#assign today = .now?date?iso_utc>
<#if !(vanafDatum??)>
  <#assign vanafDatum = today>
</#if>
<#if !(totenmetDatum??)>
  <#assign totenmetDatum = today>
</#if>

PREFIX oa:   <http://www.w3.org/ns/oa#>  
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>  
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX reva: <http://data.reva.nl/2013/07/reva#>
PREFIX rela: <http://www.digimelding.nl/2013/11/relaties#>
PREFIX gem:  <http://www.bprbzk.nl/BRP/informatiebank/tabel33#>

SELECT ?gemeenteVanInschrijvingCode ?gemeente (COUNT(?stamUri) as ?aantalRegistraties)
WHERE { 
  GRAPH ?stamUri {
    ?bsnAnnotatie oa:hasTarget ?stamUri ;
      rdf:type reva:BSNAnnotatie .

<#if gemeenteCode??>
    ?adresAnnotatie rdf:type reva:AdresAnnotatie ;
      reva:isLaatsteAdres 'marker' ;
      oa:hasTarget ?stamUri ;
      oa:hasBody ?body .

    ?body rdf:type reva:AdresBody ;
      reva:bagIdCodePlaats ?idCodeObject .
</#if>

    ?stamUri rdf:type reva:RootAnnotatie ;
      oa:annotatedAt ?tijdstempelAanmaak ;
      oa:annotatedBy ?agent .

    FILTER (
      ( strdt( substr(?tijdstempelAanmaak, 1, 10), xsd:date) >= strdt("${vanafDatum}", xsd:date) ) &&
      ( strdt( substr(?tijdstempelAanmaak, 1, 10), xsd:date) <= strdt("${totenmetDatum}", xsd:date) )
    ) .
    
    ?agent rdf:type prov:Agent .
  } 

  OPTIONAL {
    GRAPH ?stamUri {
      ?adresAnnotatie rdf:type reva:AdresAnnotatie ;
        oa:hasTarget ?stamUri ;
        oa:annotatedBy ?agent .

      ?agent foaf:organisation ?gemeenteVanInschrijvingCode .
    }
	
    GRAPH <http://www.bprbzk.nl/BRP/informatiebank/tabel33> {
      ?gemeenteObject rdf:type gem:Gemeente ;
        gem:code ?gemeenteVanInschrijvingCode ;
        gem:naam ?gemeente .
    }
  }

<#if gemeenteCode??>
  GRAPH <http://www.digimelding.nl/2013/11/relaties> {
    <http://www.kadaster.nl/gemeente/${gemeenteCode}> rdf:type rela:Gemeente ;
      rela:heeftPlaats ?idCodeObject .
  }
</#if>
}
GROUP BY ?gemeenteVanInschrijvingCode ?gemeente  
LIMIT ${limit} OFFSET ${offset}
