#!Freemarker
# Deze query geeft een result set met plaatsnamen die overeenkomen met de 
# opgegeven plaatsnaampartial (eerste karakters)
#
# Required Parameters:
#   partial  deel van de woonplaatsnaam.
# 
# Optional parameters:
#   limit              het maximum aantal te tonen resultaten
#   offset             de offset in de totale result set van waar te starten 
#                      met het tonen van resultaten.
#

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX gem:  <http://www.bprbzk.nl/BRP/informatiebank/tabel33#>
PREFIX rela: <http://www.digimelding.nl/2013/11/relaties#>

SELECT ?gemeenteRef ?plaatsCode
WHERE {
  GRAPH <http://www.digimelding.nl/2013/11/relaties> {
    ?gemeenteRef rdf:type rela:Gemeente ;
      rela:heeftPlaats ?plaatsCode .
  }
}
ORDER BY ASC(?code)
LIMIT ${limit} OFFSET ${offset}

